### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by antoyo** [jdhorwitz/fish_vars#1]
Hi.
[Just so you know, it's already built-in in the fish shell.](https://fishshell.com/docs/current/tutorial.html#tut_path)
As an alternative to:
```rust
fish_vars ~/bin /bin /josh/bin
```
You only need to do:
```bash
set -U fish_user_paths ~/bin /bin /josh/bin
```
Regards.

**Comment by jdhorwitz** [comment]
Thank you, this was more of an attempt at learning Rust.  I appreciate this! Good tip.
